help menu for some scripts

diff --git a/.local/bin/imgur b/.local/bin/imgur
--- a/.local/bin/imgur
+++ b/.local/bin/imgur
@@ -1,14 +1,26 @@
 #!/bin/bash
 
-# script to upload image to imgur.com and copy link to it
-# 
-# API Key provided by hi@ilyos.xyz;
-# replace with your own or specify yours as IMGUR_CLIENT_ID environment variable
-# to avoid limits
 default_client_id=2e66167fec8c9fb
 client_id="${IMGUR_CLIENT_ID:-$default_client_id}"
 
 ifinstalled --notify curl xclip || exit 1
+
+help_opt() {
+  NAME="${0##*/}"
+  INFO="
+$NAME: upload image to imgur and copy the link
+
+usage: $NAME (-|path|url)
+  -       read image from stdin
+  path    path to an image
+  url     url of image
+
+note: default client ID (API key) is provided. Change it in code
+      or set IMGUR_CLIENT_ID environment variable to yours
+"
+  printf "%s" "$INFO"
+}
+
 
 send() {
   curl -s  -H "Authorization: Client-ID $client_id" -F "image=$1" https://api.imgur.com/3/image.xml 2>/dev/null
@@ -28,21 +40,24 @@ upload() {
   fi
 }
 
-if [ $# -eq 0 ]; then
-  exec "$0" -
-fi
+upload_n_copy() {
+  if ! upload "$1"; then
+    notify-send "$1" "upload failed"
+    exit 3
+  elif [ -z "${xml##*success=\"0\"*}" ]; then
+    err="${xml##*<error>}"
+    err="${err%%</error>*}"
+    notify-send "$1" "$err"
+    exit 4
+  fi
 
-if ! upload "$1"; then
-  notify-send "$1" "upload failed"
-  exit 3
-elif [ -z "${xml##*success=\"0\"*}" ]; then
-  err="${xml##*<error>}"
-  err="${err%%</error>*}"
-  notify-send "$1" "$err"
-  exit 4
-fi
+  link="${xml##*<link>}"
+  link="${link%%</link>*}"
 
-link="${xml##*<link>}"
-link="${link%%</link>*}"
+  echo -n "$link" | xclip -sel clip && notify-send "$1" "uploaded & link copied"
+}
 
-echo -n "$link" | xclip -sel clip && notify-send "$1" "uploaded & link copied"
+case "$1" in
+  --help) help_opt;;
+  *) upload_n_copy "$@";;
+esac
