imgur script: enhanced & added stdin

diff --git a/.local/bin/imgur b/.local/bin/imgur
--- a/.local/bin/imgur
+++ b/.local/bin/imgur
@@ -1,26 +1,48 @@
 #!/bin/bash
 
-# script to upload image to imgur.com; and copy link to it
+# script to upload image to imgur.com and copy link to it
 # 
-# NOTE: use your own Client-ID as IMGUR_CLIENT_ID
+# API Key provided by hi@ilyos.xyz;
+# replace with your own or specify yours as IMGUR_CLIENT_ID environment variable
+# to avoid limits
+default_client_id=2e66167fec8c9fb
+client_id="${IMGUR_CLIENT_ID:-$default_client_id}"
 
-ifinstalled --notify curl jq xclip || exit 1
+ifinstalled --notify curl xclip || exit 1
 
-imgur_client_id="$(cat ~/.local/share/imgur_client_id)"
-
-jqr() {
-  jq --unbuffered --raw-output "$@"
+send() {
+  curl -s  -H "Authorization: Client-ID $client_id" -F "image=$1" https://api.imgur.com/3/image.xml 2>/dev/null
 }
 
-json="$(curl -s  -H "Authorization: Client-ID $imgur_client_id" -F "image=@$1" https://api.imgur.com/3/image)"
+upload() {
+  if [ -z "${1%%http*}" ]; then
+    # url
+    xml="$(send "$1")"
+  else
+    # file
+    if [ "$1" != "-" -a ! -f "$1" ]; then
+      notify-send "$1" "file doesn't exist"
+      exit 2
+    fi
+    xml="$(send "@$1")"
+  fi
+}
 
-status="$(echo "$json" | jqr .status)"
-
-if [ "$status" -ne 200 ]; then
-  notify-send "$(echo "$json" | jqr .data.error)"
-  exit 1
+if [ $# -eq 0 ]; then
+  exec "$0" -
 fi
 
-link="$(echo "$json" | jqr .data.link)"
-echo -n "$link" | xclip -sel clip
-notify-send "Image has been uploaded"
+if ! upload "$1"; then
+  notify-send "$1" "upload failed"
+  exit 3
+elif [ -z "${xml##*success=\"0\"*}" ]; then
+  err="${xml##*<error>}"
+  err="${err%%</error>*}"
+  notify-send "$1" "$err"
+  exit 4
+fi
+
+link="${xml##*<link>}"
+link="${link%%</link>*}"
+
+echo -n "$link" | xclip -sel clip && notify-send "$1" "uploaded & link copied"
